#!/usr/bin/env bash
set -euo pipefail

# Expect argument of full image ref, e.g.
# ghcr.io/owner/repo:tag
IMAGE_REF=$1

# Parse version from IMAGE_REF
VERSION=$(echo "$IMAGE_REF" | sed -E 's/.*:(.*)$/\1/')

# Use jq to convert ./manifest.json file into config labels (md.obsidian.plugin.v1.<field>)
# Also mapping to appropriate org.opencontainers label keys
# These labels go in the config, which is content-addressed and immutable
jq -n --arg ver "$VERSION" --slurpfile manifest ./manifest.json '{
  "created": (now | strftime("%Y-%m-%dT%H:%M:%SZ")),
  "config": {
    "Labels": {
      "org.opencontainers.image.version": $ver,
      "org.opencontainers.image.title": $manifest[0].name,
      "org.opencontainers.image.description": $manifest[0].description,
      "org.opencontainers.image.authors": $manifest[0].author,
      "org.opencontainers.image.url": $manifest[0].authorUrl,
      "org.opencontainers.image.created": (now | strftime("%Y-%m-%dT%H:%M:%SZ")),
      "md.obsidian.plugin.v1.id": $manifest[0].id,
      "md.obsidian.plugin.v1.name": $manifest[0].name,
      "md.obsidian.plugin.v1.version": $manifest[0].version,
      "md.obsidian.plugin.v1.minAppVersion": $manifest[0].minAppVersion,
      "md.obsidian.plugin.v1.description": $manifest[0].description,
      "md.obsidian.plugin.v1.author": $manifest[0].author,
      "md.obsidian.plugin.v1.authorUrl": $manifest[0].authorUrl,
      "md.obsidian.plugin.v1.isDesktopOnly": ($manifest[0].isDesktopOnly // false | tostring)
    }
  }
}' > config.json

oras push $IMAGE_REF \
  --artifact-type application/vnd.obsidian.plugin.v1+json \
  --config config.json:application/vnd.oci.image.config.v1+json \
  ./main.js:application/javascript \
  ./styles.css:text/css
